// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wired

import (
	"github.com/google/wire"

	handler2 "github.com/mecitsemerci/go-todo-app/internal/app/api/handler"
	"github.com/mecitsemerci/go-todo-app/internal/core/service"
	"github.com/mecitsemerci/go-todo-app/internal/infra/mongodb"
)

// Injectors from mongo.go:

func InitializeTodoHandler() (handler2.TodoHandler, error) {
	client, err := mongodb.ProvideMongoClient()
	if err != nil {
		return handler2.TodoHandler{}, err
	}
	todoRepository := mongodb.ProvideTodoRepository(client)
	idGenerator := mongodb.ProvideIDGenerator()
	todoService := service.ProvideTodoService(todoRepository, idGenerator)
	todoHandler := handler2.ProvideTodoHandler(todoService)
	return todoHandler, nil
}

// mongo.go:

// MongoDB Service Dependencies
var TodoRepositorySetByMongo = wire.NewSet(mongodb.ProvideTodoRepository, mongodb.ProvideMongoClient)

var TodoServiceSetByMongo = wire.NewSet(service.ProvideTodoService, TodoRepositorySetByMongo, mongodb.ProvideIDGenerator)

func InitializeHealthHandler() handler2.HealthHandler {
	return handler2.HealthHandler{}
}
