// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wired

import (
	"github.com/google/wire"
	"github.com/mecitsemerci/go-todo-app/internal/api/handler"
	"github.com/mecitsemerci/go-todo-app/internal/core/services"
	"github.com/mecitsemerci/go-todo-app/internal/pkg/mongodb"
)

// Injectors from wired.go:

func InitializeTodoController() (handler.TodoHandler, error) {
	client, err := mongodb.ProvideMongoClient()
	if err != nil {
		return handler.TodoHandler{}, err
	}
	todoRepository := mongodb.ProvideTodoRepository(client)
	idGenerator := mongodb.ProvideIDGenerator()
	todoService := services.ProvideTodoService(todoRepository, idGenerator)
	todoHandler := handler.ProvideTodoHandler(todoService)
	return todoHandler, nil
}

// wired.go:

var TodoRepositorySet = wire.NewSet(mongodb.ProvideTodoRepository, mongodb.ProvideMongoClient)

var TodoServiceSet = wire.NewSet(services.ProvideTodoService, TodoRepositorySet, mongodb.ProvideIDGenerator)

func InitializeHealthController() handler.HealthController {
	return handler.HealthController{}
}
