// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wired

import (
	"github.com/google/wire"
	"github.com/mecitsemerci/go-todo-app/internal/api/handler"
	"github.com/mecitsemerci/go-todo-app/internal/core/services"
	"github.com/mecitsemerci/go-todo-app/internal/pkg/mongodb"
)

// Injectors from mongo.go:

func InitializeTodoHandler() (handler.TodoHandler, error) {
	client, err := mongodb.ProvideMongoClient()
	if err != nil {
		return handler.TodoHandler{}, err
	}
	todoRepository := mongodb.ProvideTodoRepository(client)
	idGenerator := mongodb.ProvideIDGenerator()
	todoService := services.ProvideTodoService(todoRepository, idGenerator)
	todoHandler := handler.ProvideTodoHandler(todoService)
	return todoHandler, nil
}

// mongo.go:

// MongoDB Service Dependencies
var TodoRepositorySetByMongo = wire.NewSet(mongodb.ProvideTodoRepository, mongodb.ProvideMongoClient)

var TodoServiceSetByMongo = wire.NewSet(services.ProvideTodoService, TodoRepositorySetByMongo, mongodb.ProvideIDGenerator)

func InitializeHealthHandler() handler.HealthHandler {
	return handler.HealthHandler{}
}
