// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wired

import (
	"github.com/google/wire"
	"github.com/mecitsemerci/clean-go-todo-api/app/api/controller"
	"github.com/mecitsemerci/clean-go-todo-api/app/api/controller/v1"
	"github.com/mecitsemerci/clean-go-todo-api/app/core"
	"github.com/mecitsemerci/clean-go-todo-api/app/infra/repository"
)

// Injectors from wired.go:

func InitializeTodoControllerV1() v1.TodoController {
	dbContext := repository.ProvideDbContext()
	iTodoRepository := repository.ProvideTodoRepository(dbContext)
	iTodoService := core.ProvideTodoService(iTodoRepository)
	todoController := controller.ProvideTodoController(iTodoService)
	return todoController
}

// wired.go:

var todoServiceSet = wire.NewSet(core.ProvideTodoService, repository.ProvideTodoRepository, repository.ProvideDbContext)

func InitializeHealthController() controller.HealthController {
	wire.Bind(controller.ProvideHealthController, repository.ProvideDbContext)
	return controller.HealthController{}
}
