// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wired

import (
	"github.com/google/wire"
	"github.com/mecitsemerci/clean-go-todo-api/app/api/controller"
	"github.com/mecitsemerci/clean-go-todo-api/app/api/controller/v1"
	"github.com/mecitsemerci/clean-go-todo-api/app/core"
	"github.com/mecitsemerci/clean-go-todo-api/app/infra/adapter"
)

// Injectors from wired.go:

func InitializeTodoControllerV1() v1.TodoController {
	dbContext := adapter.ProvideDbContext()
	iTodoRepository := adapter.ProvideTodoRepository(dbContext)
	iTodoService := core.ProvideTodoService(iTodoRepository)
	todoController := controller.ProvideTodoController(iTodoService)
	return todoController
}

// wired.go:

var todoServiceSet = wire.NewSet(core.ProvideTodoService, adapter.ProvideTodoRepository, adapter.ProvideDbContext)

func InitializeHealthController() controller.HealthController {
	wire.Bind(controller.ProvideHealthController, adapter.ProvideDbContext)
	return controller.HealthController{}
}
